=== hmrc/individual-income-des-stub/resources/public/api/conf/1.0/schemas/create-employment-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "employment",
  "properties": {
    "payments": {
      "description": "The payments associated with the employment",
      "type": "array",
      "items": {
        "additionalProperties": false,
        "id": "/properties/payments/items",
        "properties": {
          "paymentDate": {
            "id": "/properties/payments/items/properties/paymentDate",
            "type": "string",
            "format": "date",
            "description": "The payment date",
            "example": "2016-01-28"
          },
          "taxablePayment": {
            "id": "/properties/payments/items/properties/taxablePayment",
            "type": "number",
            "description": "The total amount for which tax was paid",
            "example": "1000.55"
          },
          "nonTaxablePayment": {
            "id": "/properties/payments/items/properties/nonTaxablePayment",
            "type": "number",
            "description": "The total amount exempt from taxes",
            "example": "0"
          }
        },
        "required": ["paymentDate", "taxablePayment", "nonTaxablePayment"],
        "type": "object"
      }
    },
    "startDate": {
      "type": "string",
      "description": "The start date for the employment",
      "example": "2016-01-01"
    },
    "endDate": {
      "type": "string",
      "description": "The end date for the employment",
      "example": "2017-03-01"
    },
    "employerPayeReference": {
      "type": "string",
      "description": "The employer PAYE reference number",
      "example": "904/UZ00057"
    },
    "nino": {
      "type": "string",
      "description": "The employee National Insurance number",
      "example": "AA123456D"
    }
  },
  "type": "object",
  "required": ["employerPayeReference", "nino", "payments"]
}

=== hmrc/individual-income-des-stub/resources/public/api/conf/1.0/examples/create-employment-response.json
{
  "employerPayeReference": "904/UZ00057",
  "nino": "AA123456D",
  "startDate": "2016-01-01",
  "endDate": "2017-03-01",
  "payments": [
    {
      "paymentDate": "2016-01-28",
      "taxablePayment": 1000.55,
      "nonTaxablePayment": 0
    },
    {
      "paymentDate": "2016-02-28",
      "taxablePayment": 950.55,
      "nonTaxablePayment": 0
    }
  ]
}
